name: Test Project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: install npn nodesJs
        uses: actions/checkout@v3
        with:
          node-version: '24'
      - name: install dependencies
        run: npm ci 
      - name: run tests
        run: npm test
  deploy:
      needs: test
      runs-on: ubuntu-latest 
      steps:
      - name: get code
        uses: actions/checkout@v6
      - name: install npm nodeJs
        uses: actions/checkout@v3
        with:
          node-version: '24'
      - name: install dependenices
        run: npm ci
      - name: build project
        run: npm run build
      - name: deploy to server
        run: echo "Deploying to the server.." 
